<?php defined('APPLICATION') or exit();
/**
 * Articles initial configuration values
 *
 * @copyright 2015-2016 Austin S.
 * @license http://www.opensource.org/licenses/gpl-2.0.php GNU GPL v2
 */

// DO NOT EDIT THIS FILE
// All of the settings defined here can be overridden in the /conf/*.php files.

$Configuration['Articles']['ShowArticlesMenuLink'] = true;
$Configuration['Articles']['ShowArticlesSidebarMenuLink'] = true;
$Configuration['Articles']['Articles']['PerPage'] = 12;
$Configuration['Articles']['Articles']['ThumbnailWidth'] = 260;
$Configuration['Articles']['Articles']['ThumbnailHeight'] = 146;
$Configuration['Articles']['Articles']['ShowAuthorInfo'] = true;
