<?php defined('APPLICATION') or exit();

// DO NOT EDIT THIS FILE
// All of the settings defined here can be overridden in the /conf/*.php files.

$Configuration['Articles']['ShowArticlesMenuLink'] = true;
$Configuration['Articles']['Articles']['PerPage'] = 12;
$Configuration['Articles']['Articles']['ThumbnailWidth'] = 260;
$Configuration['Articles']['Articles']['ThumbnailHeight'] = 146;
$Configuration['Articles']['Articles']['ShowAuthorInfo'] = false;
